# Generated by Django 4.2.1 on 2024-09-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create'], 'verbose_name': 'Лифты', 'verbose_name_plural': 'Лифты'},
        ),
        migrations.RemoveField(
            model_name='women',
            name='husband',
        ),
    ]
